### ISSUE TITLE
Sign up issue with accpeting terms

### ISSUE THREAD

**Issue by invictusnet** [williamgomes/ticketchai.com#1]
Can't sign up says accept terms even tho terms are agreed too

**Comment by williamgomes** [comment]
I guess I need to push latest database. I will fix this issue tomorrow as I am on weekend now. Thnx.

**Comment by invictusnet** [comment]
thank you friend

**Comment by williamgomes** [comment]
@invictusnet friend i solved that issue. Actually this issue was raised for a custom jquery checkbox plugin i used in my application. Let me know if you need anything.

**Comment by williamgomes** [comment]
Take a pull before continue. Also import new .sql

**Comment by invictusnet** [comment]
works great thank you i'll be pushing a few fixes on small things your way

**Comment by invictusnet** [comment]
can't send out emails via stmp

**Comment by williamgomes** [comment]
Hey bro,

Did you get access to admin panel? Cuz u need to change SMTP settings from
there.

Best Regards.

William Gomes

**Comment by zonedoutspace** [comment]
yes i got access to backend

**Comment by zonedoutspace** [comment]
can you use gmail

**Comment by williamgomes** [comment]
Hello friends,

My gmail is: mijo.jfwg@gmail.com

Email me anytime you want. I am always online except when I am sleeping.

Best Regards.

William Gomes

**Comment by williamgomes** [comment]
Hello friend,

Sorry i misunderstood your question. Did you able to setup gmail? Please
let me know if you need any help. I will be able to help you out with this
issue.

Regards.

On Tue, Aug 18, 2015 at 12:21 PM, William Gomes <mijo.jfwg@gmail.com> wrote:

> Hello friends,
>
> My gmail is: mijo.jfwg@gmail.com
>
> Email me anytime you want. I am always online except when I am sleeping.
>
> Best Regards.
>
> William Gomes
>
> Sent from my so called smart phone
> On Aug 18, 2015 12:07 PM, "zonedoutspace" <notifications@github.com>
> wrote:
>
>> can you use gmail
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/williamgomes/ticketchai.com/issues/1#issuecomment-132084919>
>> .
>>
>


-- 
*Best regards.*

*William F. Gomes*

*Sr. Software Engineer*
*E-mail: william.gomes.joy@gmail.com <william.gomes.joy@gmail.com>*
*Skype: william.francis.gomes*

**Comment by zonedoutspace** [comment]
I put my gmail info and it doesn't send out emails

**Comment by williamgomes** [comment]
Can u give me a screen shot of the page friend. I surely can help u out.

Best Regards.

William Gomes

**Comment by zonedoutspace** [comment]
what page? i entered stmp info in admin panel

**Comment by williamgomes** [comment]
Yes, I am talking about Email Settings page of admin panel. Give me a
screen shot of that page, so that I can see what parameter u gave.

Best Regards.

William Gomes

**Comment by zonedoutspace** [comment]
https://gyazo.com/d9ab4ca0cabf53b1bf78ee30e82f7ec1
